# this config is heavily inspired from https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.travis.yml

language: php
sudo: false

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --optimize-autoloader"
        - TASK_TESTS=1
        - TASK_CS=1

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: DEPLOY=yes
        # - php: 7.0

cache:
    directories:
        - $HOME/.composer

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # display tasks configuration for a job
    - set | grep ^TASK | sort

install:
    - travis_retry composer install $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
    - composer info -D | sort

script:
    - if [ $TASK_TESTS == 1 ]; then vendor/bin/phpunit --verbose; fi
    - if [ $TASK_CS == 1 ]; then vendor/bin/php-cs-fixer --diff --dry-run -v fix; fi

before_deploy:
    # install box2
    - (mkdir -p $HOME/bin && cd $HOME/bin && curl -LSs http://box-project.github.io/box2/installer.php | php && mv box.phar box)
    - box --version

    # ensure that deps will work on lowest supported PHP version
    - composer config platform.php 2> /dev/null || composer config platform.php 7.0.0

    # update deps to highest possible for lowest supported PHP version
    - composer install $DEFAULT_COMPOSER_FLAGS --no-dev
    - composer info -D | sort

    # build phar file
    - mkdir -p build
    - php -d phar.readonly=false $HOME/bin/box build

deploy:
    provider: releases
    file: build/pimcore.phar
    skip_cleanup: true
    api_key:
        secure: atADzIIHrp1x39bYjbafN1zyhtqcH5cQMk+uVgtFlYjQjxK3ohcHv1xqd18eB8RuYqwR7ld7pT9yfmsXjh/JpG6l1ZUrYehpeHo1AIa8Yp+YWU5IZxjeby0rKpuyGntKk54ql4WTN+dAvHaPRhYD4NI/iru2SV0FLCHvxBN1Nq33Om5UU0sJz1lHMKMPPtc82ga9/Kzq7rJRN7z0SJExywrDtqkleMQjLUfRTaFrbXWpUL1j4n2RskgdNzMPSxZv41r7NM85fsybu+taReCEUpaNSJQ0dSQ9gc/wxa61haXC+7cphhInEgqnfxDoPG9GgE6gjsTRUZI5cdDPu2wMQjgDyfsv5o1XDlmx2kKBGV5Iin52nUXnz70f5amUx4hdDD8OH3HchPQojrxWEZ1RFUReTApzqeoge6VBJfbOuqGqGRtIrqZzir8tsztYo4+fzeFC7GKJInD7pgeVc80wwo+Hg2Tr47MHiKAIaR0ykV/+oVlp4eO6J7WszJjg7tGnGkKm+9LSPUlXaxR+8C7UZhQD0NF05hYJtmUbqKhbERVdQymPWJ/hg2S7n0DFiU3CRCE673fRnESuLvsjT0ehXglz5xaKs7XvBQv15ttxjlUvCWmrn6ag4OgL6wFBX4f99Xr3gJHNdXBKDTH3E1OknXuM9dYY5g3U01Yi1GG8Zrs=
    on:
        repo: pimcore/pimcore-cli
        tags: true
        condition: $DEPLOY = yes
